# Generated by Django 2.0.1 on 2019-03-21 18:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_registration',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 18, 8, 38, 829291, tzinfo=utc)),
        ),
    ]
