# Generated by Django 2.0.1 on 2019-03-21 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190321_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_registration',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 18, 25, 23, 527757, tzinfo=utc)),
        ),
    ]
