# Generated by Django 2.0.1 on 2019-03-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190321_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_registration',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
