# Generated by Django 2.2 on 2019-04-05 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20190330_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(default='default.jpg', upload_to=profiles.models.user_directory_path_photo)),
                ('status', models.CharField(blank=True, max_length=134)),
                ('about', models.TextField(blank=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('track', models.FileField(upload_to=profiles.models.user_directory_path_audio)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_audio', to='profiles.Profile')),
            ],
        ),
    ]
