# Generated by Django 2.0.1 on 2019-04-04 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20190330_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(default='default.jpg', upload_to='photos/%Y/%m/%d')),
                ('status', models.CharField(max_length=134)),
                ('about', models.TextField()),
                ('followers', models.ManyToManyField(related_name='following', to='profiles.Profile')),
            ],
        ),
    ]
