# Generated by Django 2.2 on 2019-04-04 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190404_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('track', models.FileField(upload_to='tracks/<django.db.models.fields.related.ForeignKey>/%Y/%m/%d')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_audio', to='profiles.Profile')),
            ],
        ),
    ]
